// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyCEi4v-5Y9xpnthihXcpsPgP1QQ-kxxk',
    appId: '1:727784932623:web:2fcbe4894a6549845cea7a',
    messagingSenderId: '727784932623',
    projectId: 'hope-try',
    authDomain: 'hope-try.firebaseapp.com',
    storageBucket: 'hope-try.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkRQppAQMYAnuipiC0KHdINgm5PGI1X7g',
    appId: '1:727784932623:android:04baef890826f0735cea7a',
    messagingSenderId: '727784932623',
    projectId: 'hope-try',
    authDomain: "hope-try.firebaseapp.com",
    storageBucket: 'hope-try.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0NZ3rAh6zthB466qYrjvDl6UfzRMtTPg',
    appId: '1:727784932623:ios:36cbabc48da278055cea7a',
    messagingSenderId: '727784932623',
    projectId: 'hope-try',
    storageBucket: 'hope-try.firebasestorage.app',
    iosBundleId: 'com.example.hopeTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0NZ3rAh6zthB466qYrjvDl6UfzRMtTPg',
    appId: '1:727784932623:ios:36cbabc48da278055cea7a',
    messagingSenderId: '727784932623',
    projectId: 'hope-try',
    storageBucket: 'hope-try.firebasestorage.app',
    iosBundleId: 'com.example.hopeTry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyCEi4v-5Y9xpnthihXcpsPgP1QQ-kxxk',
    appId: '1:727784932623:web:03d9ddf82907bd6d5cea7a',
    messagingSenderId: '727784932623',
    projectId: 'hope-try',
    authDomain: 'hope-try.firebaseapp.com',
    storageBucket: 'hope-try.firebasestorage.app',
  );

}