// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDaq-qPIcDShmJd-PA3plkp8IaLjMP1po',
    appId: '1:981936821405:web:a730165b6e49681c223074',
    messagingSenderId: '981936821405',
    projectId: 'reface-4e1b9',
    authDomain: 'reface-4e1b9.firebaseapp.com',
    storageBucket: 'reface-4e1b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIf9C4rSIRM6U1Uz-sYeK0SYI2JaHcLvE',
    appId: '1:981936821405:android:7f0b262f0917a9b1223074',
    messagingSenderId: '981936821405',
    projectId: 'reface-4e1b9',
    storageBucket: 'reface-4e1b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgusj0yt-MF1fd5nK_hITdXPSHXipcl6E',
    appId: '1:981936821405:ios:b86686ce46ea58ab223074',
    messagingSenderId: '981936821405',
    projectId: 'reface-4e1b9',
    storageBucket: 'reface-4e1b9.firebasestorage.app',
    iosBundleId: 'com.example.testAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgusj0yt-MF1fd5nK_hITdXPSHXipcl6E',
    appId: '1:981936821405:ios:b86686ce46ea58ab223074',
    messagingSenderId: '981936821405',
    projectId: 'reface-4e1b9',
    storageBucket: 'reface-4e1b9.firebasestorage.app',
    iosBundleId: 'com.example.testAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDaq-qPIcDShmJd-PA3plkp8IaLjMP1po',
    appId: '1:981936821405:web:cfb1f03d09e0b303223074',
    messagingSenderId: '981936821405',
    projectId: 'reface-4e1b9',
    authDomain: 'reface-4e1b9.firebaseapp.com',
    storageBucket: 'reface-4e1b9.firebasestorage.app',
  );
}
